sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t adi1916/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adi1916/react-test npm test

after_success:
  - docker build -t adi1916/multi-client ./client
  - docker build -t adi1916/multi-nginx ./nginx
  - docker build -t adi1916/multi-server ./server
  - docker build -t adi1916/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push adi1916/multi-client
  - docker push adi1916/multi-nginx
  - docker push adi1916/multi-server
  - docker push adi1916/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'complex'
  env: 'Complex-env'
  bucket_name: 'elasticbeanstalk-us-east-1-685855047331'
  bucket_path: 'docker-complex'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY